name = "Jabaxus QoL"
author = "Jabaxus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cc692687b4d8e2139c0e343aa72d2f57fe20141f01569cd98080cfc1b9c9bc9"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
