name = "Jabaxus QoL"
author = "Jabaxus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "254340f9ed28a6235376f3334f59feb64a330842ddf3523f059ad9df85241f78"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = [" 1.21.8", "1.21.9"]
