name = "Jabaxus QoL"
author = "Jabaxus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33e24286cf23b5949147dcb7137d6fa67350eac3db2e023d337bb5f0548217bd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6", "1.21.7"]
