name = "Jabaxus QoL"
author = "Jabaxus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd5254cac0f0e84732ef3be31c1229d34b2d75a236c15117104cd93e51b74148"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.4"]
