name = "Jabaxus QoL"
author = "Jabaxus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7041563bbd34ba499ff81ecc7bee1d4b97810cc08f714aa9f95b19005b67ea43"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
