name = "Jabaxus QoL"
author = "Jabaxus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a26eb2c5b3b112cf6fd4c0029ec93e70b97ae086ef64b95898d803f720e23db"

[versions]
fabric = "0.16.14"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6", "1.21.7"]
